name: Sync to Target Repository

on:
  push:
    branches:
      - master  # 监听 master 分支的推送

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Sync to Target Repository
        uses: wearerequired/git-mirror-action@master
        env:
          # 配置 SSH 私钥，用于鉴权推送到目标仓库
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        with:
          # 替换为你的 GitHub 源仓库地址（SSH 格式）
          source-repo: "git@github.com:jczsk/jczsk.github.io.git"
          # 替换为你的目标仓库地址（SSH 格式）
          destination-repo: "git@github.com:yxtcfw/yxtcfw.github.io.git"
